movieproject/movieapp/urls.py
from.import views
from django.urls import path
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')


    ]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    descr=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to ='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from.models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','descr','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie1 = movie.objects.all()
    context = {
        'movie_list': movie1
    }
    return render(request, 'movie.html', context)


def detail(request, movie_id):
    mf = movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'result': mf})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        descr = request.POST.get('descr')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie2=movie(name=name,descr=descr,year=year,img=img)
        movie2.save()
    return render(request, 'add.html')

def update(request,id):
    movies = movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'forms':form,'movies':movies})

def delete(request,id):
    if request.method=='POST':
        movies = movie.objects.get(id=id)
        movies.delete()
        return redirect('/')

    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name">
    <input type="text" name="descr" placeholder="Enter Movie Description">
    <input type="text" name="year" placeholder="Enter Movie Year">
    <input type="file" name="img" >
    <input type="submit">

</form>


{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
   Online Movie Store
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit" >

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{result.img.url}}" height="300" width="300">
        </div>
        <div class="col-md-6">
            <h2>{{result.name}}</h2>
            <h6>{{result.descr}}</h6>
            {{result.year}}<br>

            <a class="btn btn-warning" href ="{% url 'movieapp:update' result.id %}">update</a>
            <a class="btn btn-danger" href ="{% url 'movieapp:delete' result.id %}">Delete</a>


        </div>
    </div>
</div>







{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit">


</form>

movieproject/templates/movie.html
{% extends 'base.html' %}
{% block body %}
<div class ="container">
    <div class="row">
        {% for i in movie_list %}
        <div class= "col-md-3">
            <div class="card" style="width: 15rem; height: 20rem;">
                <img src="{{i.img.url}}" class="Card image cap" alt=""  width="220" height="280">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.year}}</p>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
                    </div>
            </div>

        </div>
         {% endfor %}
    </div>
</div>
{% endblock %}





<!--<img src="{{i.img.url}}" height="100" width="100">-->
<!--print everything when we run-->
<!--<{{i.id}},{{i.name}},{{i.descr}}<br><br>-->

<!--before learning url-->
<!--<a href="movie/{{i.id}}">{{i.name}} </a><br>-->

<!--url setup-->
<!--  <a href="{% url 'movieapp:detail' i.id %}">{{i.name}} </a><br>-->